use UNIVER;
SELECT FACULTY.FACULTY as 'Факультет',
    PULPIT.PULPIT as 'Кафедра',
    PROFESSION.PROFESSION as 'Специальность',
    [SUBJECT].[SUBJECT] as 'Дисциплина',
    STUDENT.[NAME] as 'Имя студента',
    CASE
WHEN PROGRESS.NOTE = 6  THEN 'Шесть'
WHEN PROGRESS.NOTE = 7 THEN 'Семь'
WHEN PROGRESS.NOTE = 8 then 'Восемь'
else 'BRUH'
end [Оценка]
FROM PROGRESS INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
    INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROFESSION on PROFESSION.FACULTY = GROUPS.FACULTY
    INNER JOIN PULPIT on PULPIT.FACULTY = GROUPS.FACULTY
    INNER JOIN FACULTY on FACULTY.FACULTY = GROUPS.FACULTY
    INNER JOIn SUBJECT on SUBJECT.PULPIT = PULPIT.PULPIT
ORDER BY 
(CASE
WHEN PROGRESS.NOTE = 7 then 1
wheN PROGRESS.NOTE = 8 then 2
WHEn PROGRESS.NOTE = 6 then 3
else 4
end
)




