use UNIVER;
SELECT STUDENT.NAME, AVG(PROGRESS.NOTE) [AVERAGE], CASE
	WHEN AVG(PROGRESS.NOTE) BETWEEN 1 AND 4 THEN 'Плохо'
	WHEN AVG(PROGRESS.NOTE) BETWEEN 5 AND 7 THEN 'Хорошо'
	WHEN AVG(PROGRESS.NOTE) BETWEEN 8 AND 10 THEN 'Отлично'
	END [RESULT]
FROM STUDENT INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
GROUP BY STUDENT.NAME