use UNIVER;
SELECT PULPIT.PULPIT_NAME as 'Кафедра', FACULTY_NAME as 'Факультет'
FROM FACULTY, PULPIT
WHERE PULPIT.FACULTY = FACULTY.FACULTY
    and PULPIT.FACULTY In (SELECT PROFESSION.FACULTY
    FROM PROFESSION
    WHERE PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%' )
